name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t backend/backend:latest .

      - name: Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: backend/backend:latest

      - name: SSH into VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kedaiprogrammer
          password: Sukses@2023

      - name: Pull the Docker image
        run: ssh kedaiprogrammer@${{ secrets.SERVER_IP }} "docker pull backend/backend:latest"

      - name: Stop and remove the old container
        run: ssh kedaiprogrammer@${{ secrets.SERVER_IP }} "docker stop backend && docker rm backend || true"

      - name: Start the Docker container
        run: ssh kedaiprogrammer@${{ secrets.SERVER_IP }} "docker run -d --name backend -p 8080:8080 -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} backend/backend:latest"
