name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t kedaiprogrammer/frontend:latest .

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kedaiprogrammer/frontend:latest

      - name: SSH into VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kedaiprogrammer
          password: Sukses@2023
          script: |
            docker stop frontend || true
            docker rm frontend || true
            docker images || true
            docker rmi $(docker images -q) || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
            docker run -d -p 4173:4173 --name frontend kedaiprogrammer/frontend:latest